apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: aitorgonzalo/recommender:latest  
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service"  
        - name: DB_NAME
          value: "movie_db"
        - name: DB_USER
          value: "aitor"
        - name: DB_PASSWORD
          value: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort