apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "movie_db"
        - name: MYSQL_USER
          value: "aitor"
        - name: MYSQL_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-persistent-storage
        - mountPath: "/docker-entrypoint-initdb.d/db_init.sql"
          subPath: db_init.sql
          name: init-db
        - mountPath: "/etc/mysql/conf.d/my.cnf"
          subPath: my.cnf
          name: init-db
        - mountPath: "/var/lib/mysql-files"  # Montar la carpeta donde está data.csv
          name: csv-storage
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p1234"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p1234"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-db
        configMap:
          name: db-init-configmap
      - name: csv-storage
        persistentVolumeClaim:
          claimName: csv-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-configmap
data:
  my.cnf: |
    [mysqld]
    local_infile=1
    secure-file-priv="/var/lib/mysql-files/"
  db_init.sql: |
    CREATE DATABASE IF NOT EXISTS movie_db;

    USE movie_db;

    CREATE TABLE movies (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        type VARCHAR(50),
        genres VARCHAR(255),
        release_year YEAR,
        imdb_id VARCHAR(15) UNIQUE,
        imdb_average_rating DECIMAL(3,1),
        imdb_num_votes INT,
        available_countries TEXT
    );

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS valoraciones (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        movie_id INT,
        rating DECIMAL(3, 1),
        comment TEXT,
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (movie_id) REFERENCES movies(id)
    );

    -- Cargar datos del archivo CSV
    LOAD DATA LOCAL INFILE '/var/lib/mysql-files/data.csv'
    INTO TABLE movies
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    (title, type, genres, release_year, imdb_id, imdb_average_rating, imdb_num_votes, available_countries);
