apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "movie_db"
        - name: MYSQL_USER
          value: "aitor"
        - name: MYSQL_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-persistent-storage
        - mountPath: "/docker-entrypoint-initdb.d"
          name: init-db
        - mountPath: "/var/lib/mysql-files"  # Montar la carpeta donde está data.csv
          name: csv-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-db
        configMap:
          name: db-init-configmap
      - name: csv-storage
        persistentVolumeClaim:
          claimName: csv-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-configmap
data:
  db_init.sql: |
    CREATE DATABASE IF NOT EXISTS movie_db;
    USE movie_db;

    CREATE TABLE IF NOT EXISTS movies (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255),
        title VARCHAR(255),
        type VARCHAR(50),
        genres VARCHAR(255),
        releaseYear INT,
        imdbId VARCHAR(20),
        imdbAverageRating DECIMAL(2, 1),
        imdbNumVotes INT,
        availableCountries TEXT
    );

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS valoraciones (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        movie_id INT,
        rating DECIMAL(2, 1),
        comment TEXT,
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (movie_id) REFERENCES movies(id)
    );

    -- Cargar datos del archivo CSV
    LOAD DATA INFILE '/var/lib/mysql-files/data.csv'
    INTO TABLE movies
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    (url, title, type, genres, releaseYear, imdbId, imdbAverageRating, imdbNumVotes, availableCountries);
