apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
      - name: apache
        image: aitorgonzalo/apache-web_kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: FLASK_SERVICE_URL
          value: "http://flask-service:5000"  
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: apache-web-service
spec:
  selector:
    app: apache-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
