apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
      - name: apache
        image: aitorgonzalo/apache-web:latest  # Usa la imagen actualizada con ambos índices
        ports:
        - containerPort: 80
        env:
        - name: FLASK_SERVICE_URL
          value: "http://flask-service:5000"  # URL del servicio Flask en el entorno Kubernetes
        command: ["/usr/local/apache2/bin/httpd"]  # Comando explícito para iniciar Apache
        args:
          - "-D"
          - "FOREGROUND"
          - "-D"
          - "KUBERNETES"
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "curl -f http://localhost:80 || exit 1"
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "mysqladmin ping -h mysql-service -u root -p1234 || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: apache-web-service
spec:
  selector:
    app: apache-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
